package com.leohapps.springsecurity.demo.pojo;

import com.fasterxml.jackson.annotation.JsonIgnore;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class JcSysPermission implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_sys_permission.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_sys_permission.PARENT_ID
     *
     * @mbg.generated
     */
    private Integer parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_sys_permission.URL
     *
     * @mbg.generated
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_sys_permission.PATH
     *
     * @mbg.generated
     */
    private String path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_sys_permission.METHOD
     *
     * @mbg.generated
     */
    private String method;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_sys_permission.COMPONENT
     *
     * @mbg.generated
     */
    private String component;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_sys_permission.NAME
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_sys_permission.ICON_CLS
     *
     * @mbg.generated
     */
    private String iconCls;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_sys_permission.KEEP_ALIVE
     *
     * @mbg.generated
     */
    private Boolean keepAlive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_sys_permission.REQUIRE_AUTH
     *
     * @mbg.generated
     */
    private Boolean requireAuth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_sys_permission.ENABLE
     *
     * @mbg.generated
     */
    private Boolean enable;


    private List<JcSysRole> roles;


    private List<JcSysPermission> children;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jc_sys_permission
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    @JsonIgnore
    public List<JcSysRole> getRoles() {
        return roles;
    }

    public void setRoles(List<JcSysRole> roles) {
        this.roles = roles;
    }

    public List<JcSysPermission> getChildren() {
        return children;
    }

    public void setChildren(List<JcSysPermission> children) {
        this.children = children;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_sys_permission.ID
     *
     * @return the value of jc_sys_permission.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_sys_permission.ID
     *
     * @param id the value for jc_sys_permission.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_sys_permission.PARENT_ID
     *
     * @return the value of jc_sys_permission.PARENT_ID
     *
     * @mbg.generated
     */
    @JsonIgnore
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_sys_permission.PARENT_ID
     *
     * @param parentId the value for jc_sys_permission.PARENT_ID
     *
     * @mbg.generated
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_sys_permission.URL
     *
     * @return the value of jc_sys_permission.URL
     *
     * @mbg.generated
     */
    @JsonIgnore
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_sys_permission.URL
     *
     * @param url the value for jc_sys_permission.URL
     *
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_sys_permission.PATH
     *
     * @return the value of jc_sys_permission.PATH
     *
     * @mbg.generated
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_sys_permission.PATH
     *
     * @param path the value for jc_sys_permission.PATH
     *
     * @mbg.generated
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_sys_permission.METHOD
     *
     * @return the value of jc_sys_permission.METHOD
     *
     * @mbg.generated
     */
    public String getMethod() {
        return method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_sys_permission.METHOD
     *
     * @param method the value for jc_sys_permission.METHOD
     *
     * @mbg.generated
     */
    public void setMethod(String method) {
        this.method = method == null ? null : method.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_sys_permission.COMPONENT
     *
     * @return the value of jc_sys_permission.COMPONENT
     *
     * @mbg.generated
     */
    public String getComponent() {
        return component;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_sys_permission.COMPONENT
     *
     * @param component the value for jc_sys_permission.COMPONENT
     *
     * @mbg.generated
     */
    public void setComponent(String component) {
        this.component = component == null ? null : component.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_sys_permission.NAME
     *
     * @return the value of jc_sys_permission.NAME
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_sys_permission.NAME
     *
     * @param name the value for jc_sys_permission.NAME
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_sys_permission.ICON_CLS
     *
     * @return the value of jc_sys_permission.ICON_CLS
     *
     * @mbg.generated
     */
    public String getIconCls() {
        return iconCls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_sys_permission.ICON_CLS
     *
     * @param iconCls the value for jc_sys_permission.ICON_CLS
     *
     * @mbg.generated
     */
    public void setIconCls(String iconCls) {
        this.iconCls = iconCls == null ? null : iconCls.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_sys_permission.KEEP_ALIVE
     *
     * @return the value of jc_sys_permission.KEEP_ALIVE
     *
     * @mbg.generated
     */
    public Boolean getKeepAlive() {
        return keepAlive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_sys_permission.KEEP_ALIVE
     *
     * @param keepAlive the value for jc_sys_permission.KEEP_ALIVE
     *
     * @mbg.generated
     */
    public void setKeepAlive(Boolean keepAlive) {
        this.keepAlive = keepAlive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_sys_permission.REQUIRE_AUTH
     *
     * @return the value of jc_sys_permission.REQUIRE_AUTH
     *
     * @mbg.generated
     */
    public Boolean getRequireAuth() {
        return requireAuth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_sys_permission.REQUIRE_AUTH
     *
     * @param requireAuth the value for jc_sys_permission.REQUIRE_AUTH
     *
     * @mbg.generated
     */
    public void setRequireAuth(Boolean requireAuth) {
        this.requireAuth = requireAuth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_sys_permission.ENABLE
     *
     * @return the value of jc_sys_permission.ENABLE
     *
     * @mbg.generated
     */
    public Boolean getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_sys_permission.ENABLE
     *
     * @param enable the value for jc_sys_permission.ENABLE
     *
     * @mbg.generated
     */
    public void setEnable(Boolean enable) {
        this.enable = enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_sys_permission
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", parentId=").append(parentId);
        sb.append(", url=").append(url);
        sb.append(", path=").append(path);
        sb.append(", method=").append(method);
        sb.append(", component=").append(component);
        sb.append(", name=").append(name);
        sb.append(", iconCls=").append(iconCls);
        sb.append(", keepAlive=").append(keepAlive);
        sb.append(", requireAuth=").append(requireAuth);
        sb.append(", enable=").append(enable);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table jc_sys_permission
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        id("ID", "id", "INTEGER", false),
        parentId("PARENT_ID", "parentId", "INTEGER", false),
        url("URL", "url", "VARCHAR", false),
        path("PATH", "path", "VARCHAR", true),
        method("METHOD", "method", "VARCHAR", true),
        component("COMPONENT", "component", "VARCHAR", false),
        name("NAME", "name", "VARCHAR", true),
        iconCls("ICON_CLS", "iconCls", "VARCHAR", false),
        keepAlive("KEEP_ALIVE", "keepAlive", "BIT", false),
        requireAuth("REQUIRE_AUTH", "requireAuth", "BIT", false),
        enable("ENABLE", "enable", "BIT", true);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table jc_sys_permission
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table jc_sys_permission
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table jc_sys_permission
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table jc_sys_permission
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table jc_sys_permission
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table jc_sys_permission
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table jc_sys_permission
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table jc_sys_permission
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table jc_sys_permission
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table jc_sys_permission
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table jc_sys_permission
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table jc_sys_permission
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table jc_sys_permission
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table jc_sys_permission
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table jc_sys_permission
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }
    }
}