package com.leohapps.springsecurity.demo.mapper;


import com.leohapps.springsecurity.demo.pojo.JcSysRole;
import com.leohapps.springsecurity.demo.pojo.example.JcSysRoleExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface JcSysRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_sys_role
     *
     * @mbg.generated
     */
    long countByExample(JcSysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_sys_role
     *
     * @mbg.generated
     */
    int deleteByExample(JcSysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_sys_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_sys_role
     *
     * @mbg.generated
     */
    int insert(JcSysRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_sys_role
     *
     * @mbg.generated
     */
    int insertSelective(JcSysRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_sys_role
     *
     * @mbg.generated
     */
    List<JcSysRole> selectByExample(JcSysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_sys_role
     *
     * @mbg.generated
     */
    JcSysRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_sys_role
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") JcSysRole record, @Param("example") JcSysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_sys_role
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") JcSysRole record, @Param("example") JcSysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_sys_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(JcSysRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_sys_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(JcSysRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_sys_role
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<JcSysRole> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_sys_role
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<JcSysRole> list, @Param("selective") JcSysRole.Column... selective);
}