package com.leohapps.springsecurity.demo.mapper;


import com.leohapps.springsecurity.demo.pojo.JcSysPermission;
import com.leohapps.springsecurity.demo.pojo.example.JcSysPermissionExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface JcSysPermissionMapper {


    List<JcSysPermission> getAllPermison();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_sys_permission
     *
     * @mbg.generated
     */
    long countByExample(JcSysPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_sys_permission
     *
     * @mbg.generated
     */
    int deleteByExample(JcSysPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_sys_permission
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_sys_permission
     *
     * @mbg.generated
     */
    int insert(JcSysPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_sys_permission
     *
     * @mbg.generated
     */
    int insertSelective(JcSysPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_sys_permission
     *
     * @mbg.generated
     */
    List<JcSysPermission> selectByExample(JcSysPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_sys_permission
     *
     * @mbg.generated
     */
    JcSysPermission selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_sys_permission
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") JcSysPermission record, @Param("example") JcSysPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_sys_permission
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") JcSysPermission record, @Param("example") JcSysPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_sys_permission
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(JcSysPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_sys_permission
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(JcSysPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_sys_permission
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<JcSysPermission> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_sys_permission
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<JcSysPermission> list, @Param("selective") JcSysPermission.Column... selective);
}